"""
ManimCE API reference, generated by introspecting the installed package.

Nothing here is hand-written: it is read from the exact Manim version we render
with (pinned in requirements.txt), so it can't drift or mix in manimgl/older API.
Scene and camera attributes are read from real instances, because some only exist
after construction (e.g. `self.camera.frame` exists only on MovingCameraScene).

Query it from the shell:
    python -m dvg.kb.api                 # summary
    python -m dvg.kb.api Arrow Text      # constructor params, bases, methods
"""

from __future__ import annotations

import builtins
import inspect
from dataclasses import dataclass, field
from functools import lru_cache


@dataclass
class ClassInfo:
    name: str
    bases: list[str]  # class names along the MRO, starting with the class itself
    init_params: set[str]  # explicit keyword-capable params across all __init__s in the MRO
    members: set[str]      # everything dir() shows on the class
    signature: str = ""


@dataclass
class ManimAPI:
    version: str
    names: set[str]                                                   # what `from manim import *` provides
    classes: dict[str, ClassInfo]
    scene_attrs: dict[str, set[str]] = field(default_factory=dict)   # scene class -> instance attrs
    camera_attrs: dict[str, set[str]] = field(default_factory=dict)  # scene class -> its camera's attrs
    builtins: set[str] = field(default_factory=lambda: set(dir(builtins)))

    def is_subclass(self, name: str, base: str) -> bool:
        info = self.classes.get(name)
        return bool(info) and base in info.bases


def _init_params(cls) -> set[str]:
    params: set[str] = set()
    for klass in cls.__mro__:
        init = klass.__dict__.get("__init__")
        if init is None:
            continue
        try:
            sig = inspect.signature(init)
        except (TypeError, ValueError):
            continue
        for p in sig.parameters.values():
            if p.kind in (p.POSITIONAL_OR_KEYWORD, p.KEYWORD_ONLY) and p.name != "self":
                params.add(p.name)
    return params


@lru_cache(maxsize=1)
def manim_api() -> ManimAPI:
    import manim
    from manim import tempconfig

    exported = getattr(manim, "__all__", None) or [n for n in dir(manim) if not n.startswith("_")]
    classes: dict[str, ClassInfo] = {}
    for name in exported:
        obj = getattr(manim, name, None)
        if inspect.isclass(obj):
            try:
                sig = str(inspect.signature(obj))
            except (TypeError, ValueError):
                sig = ""
            classes[name] = ClassInfo(name=name, bases=[k.__name__ for k in obj.__mro__],
                                      init_params=_init_params(obj), members=set(dir(obj)), signature=sig)

    api = ManimAPI(version=manim.__version__, names=set(exported), classes=classes)
    with tempconfig({"dry_run": True, "verbosity": "ERROR"}):
        for name, info in classes.items():
            if "Scene" not in info.bases:
                continue
            try:
                scene = getattr(manim, name)()
            except Exception:
                continue
            try:
                scene.setup()  # some scene types create attributes here (ZoomedScene.zoomed_camera)
            except Exception:
                pass
            api.scene_attrs[name] = set(dir(scene))
            api.camera_attrs[name] = set(dir(scene.camera))
    return api


def describe(name: str) -> str:
    import manim

    api = manim_api()
    info = api.classes.get(name)
    if info is None:
        return f"{name}: not a class exported by manim {api.version}"
    cls = getattr(manim, name)
    methods = sorted(m for m in info.members if not m.startswith("_") and callable(getattr(cls, m, None)))
    lines = [f"{name}{info.signature}", f"  bases: {' -> '.join(info.bases[1:6])}",
             f"  keyword params (incl. inherited): {', '.join(sorted(info.init_params))}",
             f"  methods ({len(methods)}): {', '.join(methods[:60])}{' ...' if len(methods) > 60 else ''}"]
    if name in api.scene_attrs:
        extra = sorted(a for a in api.scene_attrs[name] - info.members if not a.startswith("_"))
        lines.append(f"  instance-only attributes: {', '.join(extra)}")
    return "\n".join(lines)


def main() -> None:
    import sys

    api = manim_api()
    if len(sys.argv) > 1:
        for name in sys.argv[1:]:
            print(describe(name))
        return
    print(f"manim {api.version}: {len(api.names)} exported names, {len(api.classes)} classes, "
          f"scene types: {', '.join(sorted(api.scene_attrs))}")


if __name__ == "__main__":
    main()
