"""
Approach B — planner + fan-out.

A planner call lays out the whole film as strict JSON (title, a shared style, and
3-10 scene specs). A shared preamble (dvg.fanout_preamble) freezes the palette and
font sizes. Then each scene is generated by its OWN call as a one-section file
(preamble prepended), checked and rendered like any sectioned scene, and the scene
clips are concatenated in plan order. Scene calls run concurrently (capped by
--max-concurrency); a scene that fails its checks is repaired on its own, without
regenerating the others.

Pipeline per scene: LLM call -> assemble (preamble + code) -> scan_code ->
api_check -> contract (static + runtime) -> render (dvg.parallel_render) -> verify.
"""

from __future__ import annotations

import json
import re
import subprocess
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from .. import llm
from .. import parallel_render
from .. import sections as sections_mod
from .. import theme
from ..fanout_preamble import build_preamble, font_names, palette_names
from ..freeform import (_FENCE, FreeformError, api_check, build_freeform_prompt,
                        extract_narration, scan_code)
from ..generate import DEPTH_HINTS, _slug
from ..parallel_render import ParallelRenderError
from ..runlog import RunLogger, prompt_version, timed

PLANNER_MODEL = "gpt-5.4-deployment-951f1"
SCENE_MODEL = "gpt-5.4-mini-deployment-db7e5"

_SCENE_TYPES = {"Scene", "MovingCameraScene", "ThreeDScene"}
_HEX = re.compile(r"^#[0-9a-fA-F]{6}$")
_PALETTE_KEYS = ("bg", "ink", "primary", "accent", "good", "warn", "muted")
_FONT_KEYS = ("title", "body", "label")


class FanoutError(FreeformError):
    """Raised when the plan is invalid or a scene can't be produced."""


# --- planner prompt (fanout-planner-v1) -------------------------------------

_PLANNER_PROMPT = r"""
You are the director of a short explainer film (~30-35 seconds total). Given a TOPIC
and a depth, lay out the whole film as a plan that a team of animators will each build
one scene from. Pick the few conceptual parts that matter most and give each its own
scene — a clear, complete through-line that fits in half a minute, not a teaser and
not a lecture.

Return ONE strict JSON object, and NOTHING else (no markdown fences, no prose):

{
  "title": "the film's title",
  "style": {
    "palette": {"bg": "#f5f3ee", "ink": "#1e232b", "primary": "#3a6ea5",
                "accent": "#c8862b", "good": "#4f9d69", "warn": "#c25b4e",
                "muted": "#6b7280"},
    "font": "Avenir Next",
    "font_sizes": {"title": 44, "body": 30, "label": 24},
    "transition": "fade"
  },
  "scenes": [
    {
      "id": "s01",
      "goal": "what the viewer should learn in this scene",
      "visual": "the central visual metaphor / what is on screen",
      "on_screen_text": ["short", "phrases"],
      "narration": "the spoken script for this scene (ONE short sentence, ~12-18 words)",
      "scene_type": "Scene | MovingCameraScene | ThreeDScene",
      "enters_with": "empty stage",
      "leaves_with": "empty stage",
      "complexity": "light | medium | heavy"
    }
  ]
}

RULES
- 3 to 6 scenes so the whole film fits ~30-35s. Ids unique (s01, s02, ...), in order.
- Open with a short title scene; build one idea per scene; end on the takeaway.
- Keep narration VERY SHORT — ONE short sentence per scene (about 12-18 words), and
  about 80 words across the whole film. The narration is read aloud as a voiceover
  that must FIT the ~30-35s film at a natural pace; longer scripts overrun and get
  cut off.
- Every scene starts and ends on an empty stage (scenes are rendered separately and
  concatenated — nothing carries over).
- Use scene_type "ThreeDScene" only when the idea is genuinely spatial. Mark a scene
  "heavy" only if it is a real 3D or dense animation — AT MOST 2 scenes may be "heavy".
- STYLE (do not make it look like default Manim): "bg" must be LIGHT (white / off-white
  / soft light tint), "ink" must be a DARK near-black for text; the other palette
  colours must be MUTED and editorial (no neon/electric colours). All colours #rrggbb.
  "font" is one real typeface from: Avenir Next, Helvetica Neue, Optima, Gill Sans,
  Futura, Georgia, Palatino, Baskerville.
- Keep on_screen_text short; the narration carries the explanation.

Output ONLY the JSON object.
"""


def build_planner_prompt() -> str:
    return _PLANNER_PROMPT.strip()


PLANNER_PROMPT_VERSION = "fanout-planner-v3"
PLANNER_PROMPT_SHA = "c74c1f87d283"


def planner_prompt_version() -> str:
    return prompt_version(PLANNER_PROMPT_VERSION, PLANNER_PROMPT_SHA, build_planner_prompt())


# --- scene prompt (fanout-scene-v1) -----------------------------------------

_SCENE_TAIL = """\
THIS IS ONE SCENE OF A LARGER FILM — write exactly one self-contained section.
- The imports, the palette ({palette}) and the font constants ({fonts}) are ALREADY
  defined ABOVE your code. USE them; do NOT add imports or redefine them.
- Output EXACTLY this shape and nothing else — no imports, no palette constants:
      NARRATION = ["the spoken line for THIS scene"]
      SECTIONS = ["main"]
      class Generated(SCENE_TYPE):
          def construct(self):
              self.camera.background_color = PAL_BG
              for name in SECTIONS:
                  getattr(self, name)()
          def main(self):
              ...  # your animation
  where SCENE_TYPE is the scene_type from the spec (Scene / MovingCameraScene /
  ThreeDScene).
- THEME (already decided for the whole film — just use it): the background is light
  (PAL_BG). Give EVERY Text a font: Text("...", font=FONT_FAMILY, color=PAL_INK) for
  normal text; use PAL_PRIMARY / PAL_ACCENT / PAL_GOOD / PAL_WARN / PAL_MUTED for
  accents. Size text with FONT_TITLE / FONT_BODY / FONT_LABEL. Never use a light text
  colour on the light background. Reveal text with FadeIn(...) — NEVER Write(...).
- The `main` section MUST start on an empty stage and end with NO visible mobjects
  (finish with self.play(*[FadeOut(m) for m in self.mobjects])).
- Do NOT assign to self.<attr> inside main (no shared state), and do NOT call
  random.seed(...) / np.random.seed(...) — seeding is handled for you.
- Keep this scene TIGHT, to the time budget given with the scene: a few focused plays
  and short holds. Doing less per scene also keeps labels from colliding. Follow all
  the LAYOUT & LEGIBILITY and API SAFETY rules above.

OUTPUT
- Return ONLY the Python for NARRATION, SECTIONS and class Generated. No imports,
  no palette, no markdown fences, no commentary."""


def build_scene_prompt() -> str:
    """freeform-v3 guidance (minus manual seeding and its free-form example),
    plus the single-section output contract for one fan-out scene."""
    base = build_freeform_prompt()
    base = base.replace("- If you use randomness, seed it: random.seed(0).\n", "")
    head = base.split("FINAL CHECK —", 1)[0].rstrip()
    tail = _SCENE_TAIL.format(palette=", ".join(palette_names()), fonts=", ".join(font_names()))
    return head + "\n\n" + tail


SCENE_PROMPT_VERSION = "fanout-scene-v4"
SCENE_PROMPT_SHA = "be4f0b45e42f"


def scene_prompt_version() -> str:
    return prompt_version(SCENE_PROMPT_VERSION, SCENE_PROMPT_SHA, build_scene_prompt())


# --- plan validation --------------------------------------------------------

def validate_plan(data) -> list[str]:
    """Return a list of problems with a plan dict (empty = valid)."""
    problems: list[str] = []
    if not isinstance(data, dict):
        return ["the plan must be a JSON object"]
    if not isinstance(data.get("title"), str) or not data["title"].strip():
        problems.append("'title' must be a non-empty string")

    style = data.get("style")
    if not isinstance(style, dict):
        problems.append("'style' must be an object with 'palette' and 'font_sizes'")
    else:
        palette = style.get("palette")
        if not isinstance(palette, dict):
            problems.append("'style.palette' must be an object")
        else:
            for k in _PALETTE_KEYS:
                v = palette.get(k)
                if not isinstance(v, str) or not _HEX.match(v):
                    problems.append(f"'style.palette.{k}' must be a #rrggbb hex colour")
            bg = palette.get("bg")
            if isinstance(bg, str) and _HEX.match(bg) and not theme.is_light(bg):
                problems.append("'style.palette.bg' must be a LIGHT colour (white / off-white / "
                                "light tint) — not a dark Manim-style background")
            ink = palette.get("ink")
            if isinstance(ink, str) and _HEX.match(ink) and not theme.is_dark(ink):
                problems.append("'style.palette.ink' must be a DARK near-black (it is the text "
                                "colour on the light background)")
        if not isinstance(style.get("font"), str) or not style.get("font", "").strip():
            problems.append("'style.font' must be a typeface name (e.g. 'Avenir Next')")
        fonts = style.get("font_sizes")
        if not isinstance(fonts, dict):
            problems.append("'style.font_sizes' must be an object")
        else:
            for k in _FONT_KEYS:
                if not isinstance(fonts.get(k), int):
                    problems.append(f"'style.font_sizes.{k}' must be an integer")

    scenes = data.get("scenes")
    if not isinstance(scenes, list):
        return problems + ["'scenes' must be a list"]
    if not (3 <= len(scenes) <= 6):
        problems.append(f"'scenes' must have 3-6 entries (got {len(scenes)})")
    ids, heavy = set(), 0
    for i, s in enumerate(scenes):
        where = f"scenes[{i}]"
        if not isinstance(s, dict):
            problems.append(f"{where} must be an object")
            continue
        sid = s.get("id")
        if not isinstance(sid, str) or not sid:
            problems.append(f"{where}.id must be a non-empty string")
        elif sid in ids:
            problems.append(f"{where}.id '{sid}' is duplicated")
        else:
            ids.add(sid)
        for field in ("goal", "visual", "narration", "enters_with", "leaves_with"):
            if not isinstance(s.get(field), str) or not s.get(field, "").strip():
                problems.append(f"{where}.{field} must be a non-empty string")
        if not isinstance(s.get("on_screen_text"), list):
            problems.append(f"{where}.on_screen_text must be a list")
        if s.get("scene_type") not in _SCENE_TYPES:
            problems.append(f"{where}.scene_type must be one of {sorted(_SCENE_TYPES)}")
        if s.get("complexity") not in {"light", "medium", "heavy"}:
            problems.append(f"{where}.complexity must be light|medium|heavy")
        if s.get("complexity") == "heavy":
            heavy += 1
    if heavy > 2:
        problems.append(f"at most 2 scenes may be 'heavy' (got {heavy})")
    return problems


def _extract_json(text: str) -> dict:
    cleaned = _FENCE.sub("", text).strip()
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        start, end = cleaned.find("{"), cleaned.rfind("}")
        if start == -1 or end <= start:
            raise
        return json.loads(cleaned[start:end + 1])


def generate_plan(topic: str, depth: str, model: str, client, logger: RunLogger | None
                  ) -> dict:
    """One planner call + up to one repair on invalid JSON/plan. Saves plan.json."""
    system = build_planner_prompt()
    user = (f"Topic: {topic.strip()}\n{DEPTH_HINTS.get(depth, DEPTH_HINTS['standard'])}\n"
            "Produce the film plan JSON.")
    if logger:
        logger.record_prompts(system, user, planner_prompt_version())
    messages = [{"role": "user", "content": user}]
    last = ""
    for attempt in range(2):
        with timed(logger, "planner_llm", attempt=attempt + 1):
            reply, tokens, used = llm.complete(client, model, system, messages)
        if logger:
            logger.record_tokens("planner_llm", tokens, model=used, attempt=attempt + 1)
        try:
            data = _extract_json(reply)
            problems = validate_plan(data)
            if problems:
                raise FanoutError("; ".join(problems))
            if logger:
                logger.artifact("plan.json", json.dumps(data, indent=2, ensure_ascii=False) + "\n")
            return data
        except (json.JSONDecodeError, FanoutError) as exc:
            last = str(exc)
            messages.append({"role": "assistant", "content": reply})
            messages.append({"role": "user", "content":
                             f"That plan was invalid: {last}\nReturn the corrected, "
                             "complete JSON object only."})
    raise FanoutError(f"planner produced no valid plan after 2 attempts; last error: {last}")


# --- scene user message -----------------------------------------------------

def _scene_summary_line(s: dict) -> str:
    return f"  {s['id']} [{s.get('complexity', '?')}/{s.get('scene_type', '?')}]: {s['goal']}"


def build_scene_user_message(plan: dict, preamble: str, idx: int) -> str:
    """Shared prefix first (preamble + full scene list — identical across scenes, so
    it prompt-caches), then this scene's neighbours and its own spec last."""
    scenes = plan["scenes"]
    spec = scenes[idx]
    parts = [
        f"FILM: {plan['title']}",
        f"TRANSITION STYLE: {plan.get('style', {}).get('transition', 'fade')}",
        "PREAMBLE already prepended to your file (use these constants, don't redefine):",
        preamble.strip(),
        "FULL SCENE LIST (for continuity — you write ONLY your scene):",
        "\n".join(_scene_summary_line(s) for s in scenes),
    ]
    if idx > 0:
        parts.append(f"PREVIOUS SCENE ({scenes[idx - 1]['id']}) ended with: "
                     f"{scenes[idx - 1].get('leaves_with', 'empty stage')}")
    if idx < len(scenes) - 1:
        parts.append(f"NEXT SCENE ({scenes[idx + 1]['id']}) begins: {scenes[idx + 1].get('goal', '')}")
    budget = max(4, round(sum(theme.TARGET_SECONDS) / 2 / len(scenes)))
    parts.append(f"TIME BUDGET for this scene: ~{budget} seconds (the film targets "
                 f"{theme.TARGET_SECONDS[0]}-{theme.TARGET_SECONDS[1]}s across {len(scenes)} scenes). "
                 "Keep it tight.")
    parts.append("YOUR SCENE — write this one (scene_type = "
                 f"{spec['scene_type']}):\n{json.dumps(spec, indent=2, ensure_ascii=False)}")
    return "\n\n".join(parts)


def assemble_scene_file(preamble: str, scene_code: str) -> str:
    """Preamble (imports + palette + fonts) then the model's one-section code."""
    return preamble.rstrip() + "\n\n\n" + scene_code.strip() + "\n"


# --- per-scene generation ---------------------------------------------------

def _contract_check(code: str) -> None:
    import tempfile
    static = sections_mod.check_static(code)
    if static:
        raise FreeformError("section contract (static): " + "; ".join(static))
    tmp = Path(tempfile.mkdtemp(prefix="dvg_fan_check_"))
    path = tmp / "scene.py"
    path.write_text(code)
    runtime = sections_mod.check_runtime(path)
    if runtime:
        raise FreeformError("section contract (runtime): " + "; ".join(runtime))


def _generate_one_scene(idx: int, plan: dict, preamble: str, *, scene_model: str,
                        escalate_model: str | None, client, logger, max_repairs: int,
                        quality: str, strategy: str, workers, timeout: int,
                        scenes_dir: Path, media_dir: Path) -> dict:
    """Generate, check and render one scene. Returns a result dict; raises
    FanoutError (with the scene id) if it can't be produced."""
    spec = plan["scenes"][idx]
    sid = spec["id"]
    scene_num = idx + 1
    system = build_scene_prompt()
    user = build_scene_user_message(plan, preamble, idx)
    out_mp4 = media_dir / f"{sid}.mp4"

    def attempt_round(model: str, client_, prefix: str) -> dict | None:
        messages = [{"role": "user", "content": user}]
        last = ""
        for attempt in range(max_repairs + 1):
            with timed(logger, "scene_llm", attempt=attempt + 1, scene=scene_num):
                reply, tokens, used = llm.complete(client_, model, system, messages)
            if logger:
                logger.record_tokens("scene_llm", tokens, model=used,
                                     attempt=attempt + 1, scene=scene_num)
            body = _FENCE.sub("", reply).strip()
            code = assemble_scene_file(preamble, body)
            if logger:
                (scenes_dir / f"{sid}.py").write_text(code)
            try:
                with timed(logger, "scan", attempt=attempt + 1, scene=scene_num):
                    scan_code(code)
                with timed(logger, "api_check", attempt=attempt + 1, scene=scene_num):
                    api_check(code, logger, attempt + 1, scene=scene_num)
                with timed(logger, "contract_check", attempt=attempt + 1, scene=scene_num):
                    _contract_check(code)
                with timed(logger, "render", attempt=attempt + 1, scene=scene_num):
                    parallel_render.render(code, out_mp4, sections=["main"],
                                           strategy=strategy, workers=workers,
                                           quality=quality, timeout_per_unit=timeout)
                return {"id": sid, "index": idx, "code": code, "mp4": str(out_mp4),
                        "narration": (extract_narration(code) or [spec.get("narration", "")])[0]}
            except (FreeformError, ParallelRenderError) as exc:
                last = str(exc)
                feedback = (f"That scene failed:\n{last}\nReturn the corrected code for "
                            "NARRATION, SECTIONS and class Generated only.")
                if logger:
                    (scenes_dir / f"{sid}_{prefix}attempt_{attempt + 1}_feedback.txt").write_text(feedback)
                messages.append({"role": "assistant", "content": body})
                messages.append({"role": "user", "content": feedback})
        raise FreeformError(last)

    try:
        return attempt_round(scene_model, client, "")
    except FreeformError as exc:
        if escalate_model:
            esc_client = llm.make_client(escalate_model)
            try:
                return attempt_round(escalate_model, esc_client, "escalate_")
            except FreeformError as exc2:
                raise FanoutError(f"scene {sid} failed after repairs and escalation: {exc2}")
        raise FanoutError(f"scene {sid} failed after {max_repairs + 1} attempts: {exc}")


# --- assembly ---------------------------------------------------------------

def _concat_videos(mp4s: list[Path], out_mp4: Path, tmp: Path) -> None:
    out_mp4.parent.mkdir(parents=True, exist_ok=True)
    listing = tmp / "scenes_concat.txt"
    listing.write_text("".join(f"file '{p}'\n" for p in mp4s))
    proc = subprocess.run(
        ["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", str(listing),
         "-c", "copy", str(out_mp4)], capture_output=True, text=True)
    if proc.returncode != 0 or not out_mp4.exists():
        raise FanoutError(f"concatenating scene clips failed:\n{(proc.stderr or '')[-1200:]}")


# --- orchestration ----------------------------------------------------------

def generate_fanout(topic: str, *, planner_model: str = PLANNER_MODEL,
                    scene_model: str = SCENE_MODEL, escalate_model: str | None = None,
                    max_concurrency: int = 4, max_repairs: int = 3, quality: str = "l",
                    depth: str = "standard", strategy: str = "sequential", workers=None,
                    timeout: int = 240, logger: RunLogger | None = None) -> tuple[str, str]:
    """Plan the film, generate each scene concurrently, render and concatenate.
    Returns (concatenated_scene_py, output_mp4_path)."""
    if not topic or not topic.strip():
        raise FanoutError("topic must be a non-empty string")
    import tempfile

    planner_client = llm.make_client(planner_model)
    with timed(logger, "plan"):
        plan = generate_plan(topic, depth, planner_model, planner_client, logger)

    preamble = build_preamble(plan.get("style"))
    scene_client = llm.make_client(scene_model)
    run_dir = logger.dir if logger else Path(tempfile.mkdtemp())
    scenes_dir = run_dir / "scenes"
    scenes_dir.mkdir(parents=True, exist_ok=True)
    media_dir = Path(tempfile.mkdtemp(prefix="dvg_fanout_media_"))

    n = len(plan["scenes"])
    results: dict[int, dict] = {}
    errors: dict[int, str] = {}

    def work(idx: int):
        try:
            results[idx] = _generate_one_scene(
                idx, plan, preamble, scene_model=scene_model, escalate_model=escalate_model,
                client=scene_client, logger=logger, max_repairs=max_repairs, quality=quality,
                strategy=strategy, workers=workers, timeout=timeout, scenes_dir=scenes_dir,
                media_dir=media_dir)
        except FanoutError as exc:
            errors[idx] = str(exc)

    with ThreadPoolExecutor(max_workers=max(1, min(max_concurrency, n))) as ex:
        list(ex.map(work, range(n)))

    if errors:
        report = "\n".join(f"- scene {plan['scenes'][i]['id']}: {msg}"
                           for i, msg in sorted(errors.items()))
        raise FanoutError(f"{len(errors)}/{n} scene(s) failed; no partial video produced:\n{report}")

    ordered = [results[i] for i in range(n)]
    out = Path("media/videos/freeform-fanout") / f"{_slug(topic)}.mp4"
    tmp = Path(tempfile.mkdtemp(prefix="dvg_fanout_concat_"))
    with timed(logger, "assemble"):
        _concat_videos([Path(r["mp4"]) for r in ordered], out, tmp)

    scene_py = "\n\n# " + "=" * 70 + "\n\n".join(r["code"] for r in ordered)
    narration = [r["narration"] for r in ordered]
    if logger:
        logger.artifact("scene.py", scene_py)
        logger.artifact("narration.json",
                        json.dumps(narration, indent=2, ensure_ascii=False) + "\n")
    return scene_py, str(out)


# --- CLI entry point --------------------------------------------------------

def run(args) -> None:
    from ..generate import _topic_param

    planner_model = args.planner_model or PLANNER_MODEL
    scene_model = args.scene_model or args.model or SCENE_MODEL
    print(f"Planning + fanning out scenes for: {args.topic!r} … "
          f"(planner={planner_model}, scenes={scene_model}, "
          f"render-strategy={args.render_strategy})")
    logger = RunLogger("freeform-fanout", args.topic, {
        "depth": args.depth, "planner_model": planner_model, "scene_model": scene_model,
        "escalate_model": args.escalate_model, "quality": args.quality,
        "render_strategy": args.render_strategy, "workers": args.workers,
        "max_concurrency": args.max_concurrency, **_topic_param(args)})
    try:
        code, video = generate_fanout(
            args.topic, planner_model=planner_model, scene_model=scene_model,
            escalate_model=args.escalate_model, max_concurrency=args.max_concurrency,
            quality=args.quality, depth=args.depth, strategy=args.render_strategy,
            workers=args.workers, logger=logger)
    except Exception as exc:
        logger.finish(False, error=str(exc),
                      extra={"scene_prompt_version": scene_prompt_version()})
        raise SystemExit(f"Fan-out generation failed: {exc}")

    out = Path(args.out) if args.out else Path("examples/generated") / f"{_slug(args.topic)}.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(code)
    logger.save_video(video)
    from ..narrate import apply_if_requested
    apply_if_requested(args, logger)
    logger.finish(True, extra={"scene_prompt_version": scene_prompt_version()})
    print(f"Wrote concatenated scenes: {out}")
    print(f"Rendered: {video}")
    print(f"Run logged at {logger.dir}")
