"""Approach B — planner + fan-out (stub; implemented on feat/freeform-fanout).

A planner call produces a strict-JSON plan; each scene is then generated by its
own call (one-section file, shared preamble), checked, and rendered through the
parallel engine (dvg.parallel_render). Scene clips are concatenated in plan order.
"""

from __future__ import annotations


def run(args) -> None:
    raise NotImplementedError(
        "freeform-fanout (approach B) is implemented on branch feat/freeform-fanout")
